import {page,p,section as s,steps,table,links} from './helpers.js';
export const accountPages={
access:page('Account and access','Your identity. Your workspace. Your holder level.',
s('holder','One account, a connected workspace',p('Your OMNIA account brings your saved preferences, followed companies and supported alert connections together. Holder access starts at 100,000 $OMNIA for the full released website. Higher levels expand capacity and beta priority.'))+
s('availability','Before the token launch',p('The token has not launched and holder verification is not active. Full access currently uses the authorized team wallet. You can explore the public experience and the JEV presentation while holder access is being prepared.'))+
s('account','Sign in',steps(['Use Sign in in the workspace header.','Complete the account flow and review the connected wallet.','Access is verified by the server. Your wallet never needs to send a token transfer to sign in.']))+
s('devices','Keep your setup',p('Supported preferences are saved to your account. Browser-specific settings and uploaded sounds may need to be added again on another device.'))+
links([['holders','Holder levels'],['settings','Settings'],['developer-api','Future developer access']]),{updated:'2026-09-25'}),
settings:page('Settings','Your profile, access, alerts and reading preferences.',s('identity','Account connections',p('Review the identity and wallet shown before linking a service. Use only the connection flow opened by OMNIA. Never enter a seed phrase in a support message.'))+s('delivery','Alerts and integrations',p('Open Alerts. Following alerts uses your selected companies and profiles with the OMNIA Telegram bot. Panel alerts uses each panel’s filters and your Telegram or Discord destinations. Each channel keeps its own selection.'))+s('appearance','Appearance',p('Choose Compact or Comfortable feed density, Standard or Large text, and device-based or Reduced motion. Review the sample, then select Save appearance. These preferences are saved with your account.'))+s('profile','Profile and access',p('Your saved display name appears when the account loads. Unsaved edits stay in place during refreshes. Wallet & access distinguishes a verified result from a check that could not complete; use Retry access check after a connection error.'))+s('panel','Panel preferences',p('Keywords, media and sound are configured with each panel’s gear. Panel delivery is saved in Discord / Telegram → Choose destinations. The OMNIA bot uses its own Following and schedule settings.'))+links([['integrations','Connect Discord or your own Telegram bot'],['telegram','Configure Telegram'],['sounds','Panel sounds'],['workspaces','Save a workspace']])),
telegram:page('OMNIA Telegram bot','Receive company alerts through the OMNIA bot, without supplying your own bot token.',s('connect','Connect your destination',steps(['Sign in and open <strong>Settings → Alerts → Following alerts</strong>.','Choose Connect and open the bot link. Connection links expire after ten minutes.','Start the bot, return to OMNIA and confirm the destination shown.','Use the test control to check delivery to your destination.']))+s('selection','Choose what arrives',p('Open Following and use each company’s Telegram controls. Enable the companies, platforms and profiles you want. Review Reddit ranking preferences separately. These existing alerts follow your Following selections and schedule. To use a panel instead, open Settings → Alerts → Panel alerts, choose Add OMNIA bot, then select it under the panel’s Discord / Telegram → Choose destinations and Save alerts. Adding the destination alone sends nothing. Test the selected panel before changing your existing Following → Telegram controls; leaving both enabled may send overlapping alerts.'))+s('connection','Disconnect or reconnect',p('Disconnecting Telegram stops this managed destination from sending. After linking again, remove the previous OMNIA bot destination from Panel alerts, add it again and reselect it in your panels. This prevents old rules from following a replacement chat.'))+s('schedule','Following alert schedule',table(['Setting','Behavior'],[['Instant','Eligible events are queued for delivery as they arrive.'],['Hourly or daily','Delivery follows the selected digest schedule.'],['Quiet hours','Delivery respects the configured quiet window and timezone.']]))+s('message','Read an alert',p('The compact message includes company context, source action, author and available text. Replies and quotes can include expandable context. Use Original source for the public post and Open in OMNIA for the app. Automatic image attachments and link previews are disabled in the compact format.'))+s('missing','When an alert is missing',p('Check connection status, company and platform selection, schedule and quiet hours. A feed record is not proof of Telegram delivery. Missing source content, duplicate prevention and delivery failures can affect an event. A successful test confirms the destination; it does not confirm every collector.'))+links([['integrations','Use your own bot or webhook'],['following','Manage delivery selection'],['troubleshooting','Troubleshoot alerts']])),
sounds:page('Panel sounds','Choose a distinct alert for each panel.',s('enable','Turn sound on',steps(['Enable sound in the workspace toolbar.','Open a panel’s gear and choose a sound.','Set a cooldown, then apply your settings.']))+s('choices','Available sounds',table(['Type','Choices'],[['Synthesized','Pulse, Bell, Chime'],['Audio files','Glass, Click, Confirm, Open, Drop, Bong, Pluck']]))+s('custom','Use your own sound',p('Upload a supported MP3, WAV, OGG, M4A or WebM file within the displayed 64 KB limit. Keep it short: playback is limited to ten seconds. A custom sound saved in this browser may need to be added again on another device.'))+s('timing','When it plays',p('Sound is for new matching arrivals after the panel starts. Loading its initial history does not play an alert for every item. Cooldown choices are 5, 15, 30 or 60 seconds, or 5 minutes. Events skipped during cooldown are not queued for later beeps.'))+s('silent','If the panel is silent',p('Interact with the page to allow browser audio. Check workspace sound, panel sound, browser mute and device volume. A returned historical item may not count as a new arrival.'))),
};
