import {page,p,section as s,steps,table,links} from './helpers.js';
const exampleShot=(name,width,height,alt)=>`<figure class="doc-shot"><a href="/assets/docs/${name}-hd.png" data-doc-image aria-label="Enlarge: ${alt}"><span class="doc-shot-frame" style="width:${width/2}px;--shot-native-width:${width}px;aspect-ratio:${width}/${height}"><img src="/assets/docs/${name}-hd.png" alt="${alt}" loading="lazy" decoding="async" width="${width}" height="${height}" style="width:100%"></span></a><figcaption>Example setup. No credentials or live delivery shown.</figcaption></figure>`;
export const deliveryPages={
discord:page('Connect Discord','Send matching panel updates to a Discord text channel.',
s('webhook','Create the webhook',steps(['In Discord, open your server’s <strong>Settings → Integrations → Webhooks</strong>. You need permission to manage webhooks.','Create a webhook, choose the destination text channel and copy its URL.','Keep the URL private. It authorizes posting to that channel.']))+
s('connect','Connect in OMNIA',steps(['Open <strong>Settings → Alerts → Panel alerts</strong> and select <strong>Discord</strong>.','Give the destination a recognizable name and paste the webhook URL.','Select <strong>Connect destination</strong>. OMNIA checks the webhook before saving it.','Select <strong>Test</strong> and confirm the test message in Discord. Wait one minute before repeating a test.']))+
exampleShot('integrations-discord',1920,1862,'Discord destination form with name and webhook fields')+s('activate','Choose a panel',p('Open the gear on a news panel, expand Discord / Telegram and Choose destinations, select this destination and save. A connected webhook receives no panel alerts until a panel is linked.'))+
s('replace','Change or revoke a webhook',p('If a webhook is deleted or exposed, replace it in Discord. Remove the old destination in OMNIA, connect the replacement and select it again in the required panels.'))+
p('<a href="https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks" target="_blank" rel="noopener noreferrer">Discord’s official webhook guide ↗</a>')+links([['panel-delivery','Send a panel'],['delivery-status','Check delivery'],['integrations','Tiers and limits']])),
 'telegram-custom':page('Connect your Telegram bot','Send matching panel updates to a group or channel you manage.',
s('bot','Prepare your bot',steps(['Open the verified <strong>@BotFather</strong> account in Telegram. Use <strong>/newbot</strong> and follow its setup instructions.','Keep the resulting bot token private. Use a dedicated bot for this destination setup.','Add your bot to the destination group or channel. In a channel, make it an administrator with permission to post. In a group, allow it to send messages.']))+
s('destination','Identify the destination',p('For a public channel, enter its <strong>@channelusername</strong>. For a private channel or group, enter the exact numeric chat ID supplied by its administrator or a trusted bot-management tool. Preserve the minus sign and any -100 prefix. A channel invite link, phone number or personal username is not a chat ID.')+p('Private groups and channels require this ID before you can connect them. OMNIA does not currently discover it for you. Do not paste a bot token into a third-party ID lookup site.'))+
s('connect','Connect in OMNIA',steps(['Open <strong>Settings → Alerts → Panel alerts</strong> and select <strong>Telegram</strong>.','Enter a destination name, your bot token and the group or channel ID.','Select <strong>Connect destination</strong>. OMNIA checks the bot, destination and posting permissions.','Select <strong>Test</strong>, then check the destination in Telegram.']))+
exampleShot('integrations-telegram',1920,2020,'Telegram destination form with bot token and channel or group ID fields')+s('messages','What arrives',p('Panel delivery sends compact text with source links. It does not attach images automatically. Long content can be shortened to fit the provider’s message limit; open the original source for the complete post.'))+
s('replace','Replace a token',p('If the token is exposed, revoke it through BotFather. Remove the old destination in OMNIA, connect it with the new token and select it again in your panels.'))+
p('<a href="https://core.telegram.org/bots/tutorial" target="_blank" rel="noopener noreferrer">Telegram’s official bot setup guide ↗</a>')+links([['panel-delivery','Send a panel'],['telegram','Use the OMNIA bot instead'],['delivery-status','Check delivery']])),
'panel-delivery':page('Send a panel','Use your panel’s filters for Discord and Telegram alerts.',
s('before','Before you start',p('From your full-access workspace, connect and test a destination in Settings → Alerts → Panel alerts. For the OMNIA bot, link and confirm Telegram in Settings → Alerts → Following alerts, then choose Add OMNIA bot in Panel alerts.'))+
s('setup','Select destinations',steps(['Open the panel gear. Select <strong>Latest news</strong> as Content, then choose a preset or set your own filters.','Set <strong>Token relationship → Any collected content</strong>.','Expand <strong>Discord / Telegram → Choose destinations</strong> and select one or more saved Discord or Telegram destinations.','Select <strong>Save alerts</strong>. Apply panel changes to keep the visible panel and its delivery rules aligned.']))+
exampleShot('panel-delivery',1200,1166,'Panel delivery with Discord and Telegram destinations selected')+s('behavior','What the rule sends',p('Saved rules run on the server while your browser is closed. They evaluate new eligible events against the saved panel filters. Preview history is not replayed as a batch of alerts. The OMNIA bot destination uses your linked private chat; no personal bot token is required. Existing Following alerts keep their settings, so review them after testing panel delivery to avoid overlapping alerts. Following digest schedules and quiet hours do not control panel delivery. Top today, Tokens and token-relationship filters are not supported for panel delivery.'))+
s('changes','Change or stop delivery',table(['Action','Result'],[['Change panel filters and Apply','Updates delivery filters for a panel with a saved delivery rule.'],['Clear every destination and Save alerts','Stops that panel’s external delivery.'],['Pause a destination in Settings','Pauses new sends to it; queued alerts can resume later.'],['Remove a destination in Settings','Removes that connection and its queued deliveries.']]))+
s('scope','Sound and window controls',p('Panel sound, media display and window layout affect the workspace. They do not control external alert frequency. Closing the browser or a panel window does not cancel a saved server delivery rule.'))+
links([['discord','Connect Discord'],['telegram-custom','Connect a Telegram bot'],['delivery-status','Understand delivery status']])),
'delivery-status':page('Delivery & troubleshooting','Check the connection, the saved rule and the destination.',
s('status','Read the destination status',table(['Status','Meaning / next step'],[['Ready','The destination is configured. Use Test to confirm it can receive now.'],['Paused','Delivery is disabled for this destination. Resume when ready.'],['Rate limited','The provider requested a delay. The queue schedules another attempt.'],['Needs attention','The provider rejected delivery. Check credentials and posting permissions.'],['Unconfirmed','OMNIA could not verify whether a send completed. Check the destination before trying again.']]))+
s('missing','No message arrived',steps(['Run one connection test from Settings → Alerts → Panel alerts. A successful test checks delivery to that destination, not the source collectors.','Check that the destination is enabled and selected in the panel’s saved Discord / Telegram → Choose destinations rule.','Check that a new event matches the panel’s content, coverage, companies, platforms, event types and keywords.','Check your current access and destination allowance. Expired or unavailable balance verification holds holder-based delivery, including pending sends.','If the provider is rate limited, allow the queue to recover. Do not repeatedly recreate the destination.']))+
s('errors','Connection problems',table(['Problem','What to do'],[['Discord webhook rejected','Use a current incoming webhook URL for the intended channel. Create a replacement if it was revoked.'],['Telegram permission rejected','Add the bot to the group, or grant channel posting permission. Check the exact chat ID.'],['Destination already connected','Use the saved destination. The same channel cannot be added twice to the same account.'],['Limit reached','Remove an unused destination or check your tier. Paused destinations still count.'],['Could not load destinations','Retry when the connection returns. An error does not mean your saved connections were deleted.']]))+
s('limits','Understand delivery limits',p('Destination allowance is not a messages-per-second allowance. Sends are paced by OMNIA and by each provider. Multiple panels matching the same event for the same destination are deduplicated. Large bursts may wait in the queue; delivery time is not guaranteed.'))+
s('support','Report an issue',p('Include the platform, destination name, panel name, approximate time and visible status. Do not include webhook URLs, bot tokens, sign-in tokens or wallet recovery words.'))+links([['integrations','Tiers and connections'],['panel-delivery','Review the saved rule'],['telegram','Troubleshoot the OMNIA bot']]))
};

deliveryPages['panel-delivery'].updated='2026-09-25';
