import {page,p,section as s,table,links,escape} from './helpers.js';
import {actions,trackers,research} from './jev-model.js';

const options={updated:'2026-09-25',theme:'jev'};
const figure=(name,alt)=>`<figure class="jev-art"><a href="/assets/docs/jev-${name}-v2.png" data-doc-image aria-label="Enlarge artwork: ${escape(alt)}"><span class="doc-shot-frame" style="--shot-native-width:1672px;aspect-ratio:1672/941"><img src="/assets/docs/jev-${name}-v2.png" width="1672" height="941" style="width:100%" alt="${escape(alt)}" ${name==='vision'?'fetchpriority="high"':'loading="lazy"'} decoding="async"></span></a></figure>`;
const note=text=>`<p class="jev-note">${text}</p>`;
const card=(index,title,text)=>`<article class="jev-principle"><span>${index}</span><h3>${title}</h3><p>${text}</p></article>`;
const flow=items=>`<ol class="jev-flow">${items.map(([title,text],i)=>`<li><span>0${i+1}</span><strong>${title}</strong><p>${text}</p></li>`).join('')}</ol>`;
const details=(title,body)=>`<details class="jev-details"><summary>${title}<span aria-hidden="true">+</span></summary><div>${body}</div></details>`;
const pathways=`<div class="jev-pathways"><a href="#/jev-news"><span>01 / PERCEPTION</span><h2>JEV News</h2><p>Every source. A clearer picture.</p><b>Explore the intelligence →</b></a><a href="#/jev-trading"><span>02 / DECISION</span><h2>JEV Trading</h2><p>Context in. Decisions with intent.</p><b>Explore the decision layer →</b></a></div>`;
const neuronDiagram=`<div class="jev-neurons" aria-label="Conceptual decision flow: evidence, specialist questions, strategy and action"><div><span>THE INPUT</span><strong>Evidence + market state</strong><p>Source records, identity, time and current position.</p></div><div class="jev-neuron-grid">${['Relevance','Identity','Liquidity','Market flow','Risk','Position'].map(x=>`<span>${x}</span>`).join('')}</div><div><span>THE POLICY</span><strong>Your parameters. One decision.</strong><p>Thresholds, permitted actions and exposure limits.</p></div></div>`;

export const intelligencePages={
jev:page('JEV','Intelligence that connects. Decisions that adapt.',
 figure('vision','OMNIA eye within a neural brain, connecting NVIDIA, Pixel Cat, Cashcat and flybody references to company context, narratives and Robinhood, Solana and BSC.')+
 `<div class="jev-manifesto"><span class="jev-kicker">THE OMNIA INTELLIGENCE LAYER</span><p>The world moves in fragments.<br><strong>JEV brings the picture together.</strong></p></div>`+
 p('A release on GitHub. A conversation on Reddit. A video, a headline, a shift in onchain activity. The vision for JEV is one continuous path from these observations to context, and from context to decisions governed by your parameters.')+
 pathways+
 s('connected','One connected intelligence.',flow([['Capture','Preserve the original record and its identity.'],['Understand','Extract entities, events, relationships and evidence.'],['Evaluate','Combine the story with the state of the market.'],['Respond','Apply the strategy and re-evaluate as evidence changes.']]))+
 `<div class="jev-principles">${card('01','Source-connected.','Every interpretation keeps a route back to the record behind it.')}${card('02','Context-sensitive.','A new observation can change the decision within the strategy’s limits.')}${card('03','Inspectable.','Inputs, evidence, model versions and policy explain how a result was formed.')}</div>`+
 note('JEV News and JEV Trading are in private beta development. These pages describe their architecture and intended experience; execution follows the roadmap.')+
 links([['jev-pipeline','Follow the complete information flow'],['jev-research','Explore the research'],['holders','Holder access'],['roadmap','Release roadmap']]),options),

 'jev-news':page('JEV News','From a fragment to the full story.',
 figure('news','JEV News concept: Pixel Cat, Cashcat, NVIDIA, flybody research, Reddit and YouTube source panels feed a neural network of entities, events, sources and context.')+
 p('JEV News is the perception layer: identify what happened, who is involved, where the evidence came from and how the story connects. Its design preserves the original source while adding a structured layer that the rest of OMNIA can use.')+
 s('metadata','Know what. Know who. Know where.',`<div class="jev-metadata-grid">${[
 ['What','Event type, claim, product, topic and what changed.'],['Who','Author, speaker, organization and each participant’s role.'],['Where','Platform, original URL, repository or community; geographical place only when supported.'],['When','Published, observed and analyzed times, kept separately.'],['How it connects','Entity aliases, related records, narrative and evidence for each relationship.'],['How certain','Validation state, missing context and separate assessments for each match.']
 ].map(([title,text])=>`<article><span>${title}</span><p>${text}</p></article>`).join('')}</div>`)+
 s('extraction','How the metadata is formed.',flow([['Normalize','The collector supplies native IDs, text, URLs and timestamps.'],['Extract','An extraction model identifies candidate entities, roles and claims.'],['Resolve','Compare names and references with known identities and related records.'],['Validate','Structured questions check attribution and support.']])+
 p('Native metadata comes from the source. Semantic metadata comes from analysis. A reported claim remains attributed to its speaker; a repost adds distribution, and a reply keeps its own author. A missing place, transcript or contract remains unknown.')+
 details('Inspect an example evidence record',`<div class="jev-evidence"><span>ILLUSTRATIVE RECORD</span><blockquote>“Atlas releases Orion v2 with a new developer integration.”</blockquote><dl><dt>Entity</dt><dd>Orion · product</dd><dt>Actor</dt><dd>Atlas · publisher</dd><dt>Event</dt><dd>Software release · version 2</dd><dt>Evidence</dt><dd>The release statement, its native ID and original URL</dd><dt>Place</dt><dd>Not stated</dd><dt>Token link</dt><dd>Unresolved until chain and contract evidence are available</dd></dl></div>`))+
 s('trackers','Different sources. One shared language.',p('Choose a source to see the metadata it contributes and how the enrichment can return to its tracker.')+
 `<div class="jev-tracker-explorer" data-jev-trackers><div class="jev-source-buttons" aria-label="Choose a source">${trackers.map((t,i)=>`<button type="button" data-jev-source="${t.id}" aria-pressed="${i===0}">${t.icon?`<img src="/assets/product-platforms/${t.icon}.svg" alt="" width="16" height="16">`:''}${t.name}</button>`).join('')}</div><div data-jev-source-detail aria-live="polite"></div></div>`)+
 s('narratives','A story can travel through many links.',p('Exact URLs establish direct references. Shared entities, event details, aliases and semantic similarity find related candidates across different posts. JEV’s design keeps “same narrative” separate from “same token”: contracts remain identified by chain and address.')+
 p('Several tokens can reference the same story without being the same project. Two tokens called STUPID INU, or sharing SI as a ticker, require independent link evidence. A candidate match stays distinct from an accepted association.')+
 `<div class="jev-story-strip"><span>Original source</span><i>→</i><span>Related reports</span><i>→</i><span>Shared narrative</span><i>→</i><span>Separate token identities</span></div>`)+
 s('handoff','Context that Trading can inspect.',p('The handoff carries the narrative reference, evidence links, entities, publication times, validation state and the strength of each token association. JEV Trading combines that context with fresh market data and position state. A popular story alone does not authorize an entry.'))+
 links([['jev-pipeline','How enrichment reaches every tracker'],['jev-trading','Follow the trading decision'],['jev-research','Research behind the design']]),options),

 'jev-trading':page('JEV Trading','Read the context. Re-evaluate the move.',
 figure('trading','JEV Trading concept: news and liquidity, volume, risk and position parameters feed the OMNIA neural core, with execution paths to Robinhood, Solana and BSC and market-state feedback.')+
 p('The trading architecture combines the story behind a token with the state of its market. Specialist evaluations examine the inputs; your strategy determines which actions are allowed. When liquidity, flow, risk or the narrative changes, the next evaluation uses the updated context.')+
 s('neurons','Specialist questions. A coordinated decision.',neuronDiagram+
 p('“Neurons” describes the specialist evaluation nodes in this workflow. Each asks a bounded question: is the story relevant, is the identity supported, is liquidity sufficient, has flow deteriorated? These nodes are application-level responsibilities, not a map of individual model neurons.')+
 `<div class="jev-principles">${card('CHOICE','Select a category.','Choose among explicit alternatives, such as supported, conflicting or unresolved.')}${card('SCORE','Assess a dimension.','Evaluate a defined scale with criteria appropriate to the task.')}${card('NOUL','Check a condition.','Answer a bounded yes/no question and retain its uncertainty.')}</div>`+
 p('Independent questions can be evaluated together; dependent checks follow their prerequisites. Model assessments feed the strategy, while hard limits control exposure, permissions and execution. User thresholds are strategy settings; they do not directly rewrite the model’s learned weights.'))+
 s('parameters','The parameters behind the decision.',`<div class="jev-parameter-list">${[
 ['Market','Price, market cap, liquidity, buys, sells, volume and change over explicit time windows.'],
 ['Ownership','Holder distribution, creator exposure, concentration and source-reported trader classifications.'],
 ['Risk','Mint / freeze permissions, taxes, locks, burns and provider risk flags.'],
 ['Identity & lifecycle','Chain, contract, pool, creator, launch phase and migration state.'],
 ['Narrative & social','Source identity, linked evidence, freshness, novelty and changes to the story.'],
 ['Position & policy','Exposure, entry budget, permitted actions, take-profit stages, stop condition and slippage limit.']
 ].map(([title,text],i)=>`<article><span>0${i+1}</span><div><h3>${title}</h3><p>${text}</p></div></article>`).join('')}</div>`+
 note('Data retains its source, time window and validation state. Missing fields and provider flags are not independent onchain conclusions.'))+
 s('seven-labels','Seven labels. An explicit purpose.',p('Select a label to inspect its meaning, inputs and next step. TP groups the five take-profit stages.')+
 `<div class="jev-action-explorer" data-jev-actions><div class="jev-action-buttons" aria-label="Decision labels">${actions.map((a,i)=>`<button type="button" data-jev-action="${a.id}" aria-pressed="${i===0}" style="--action-color:${a.color}">${a.label}</button>`).join('')}</div><div data-jev-action-detail aria-live="polite"></div></div>`)+
 s('adaptive','Same token. New evidence. A different decision.',`<div class="jev-scenario"><span class="jev-kicker">ILLUSTRATIVE STRATEGY FLOW</span><ol><li><strong>SKIP</strong><p>A narrative is visible, but its contract association is unresolved.</p></li><li><strong>BUY candidate</strong><p>Identity is supported and the configured entry checks pass.</p></li><li><strong>HOLD → TP</strong><p>An existing position remains valid, then reaches an exit stage.</p></li><li><strong>SL or HOLD MOONBAG</strong><p>A protective condition triggers an exit, or the strategy retains a bounded remainder after confirmed partial fills.</p></li></ol></div>`+
 p('The sequence depends on evidence and position state. The engine can reject an attractive-looking setup, keep monitoring it, or change course when its supporting conditions disappear.'))+
 s('execution','From a decision to a confirmed result.',p('The execution path adds quote checks, action authorization, order submission, receipt tracking and reconciliation. A signal, a submitted order and a confirmed fill are separate states. PROFIT follows reconciled accounting, including fees.')+
 note('The local beta contains real market observation and tracing. Its animated action cards are presentation examples; live decision automation and order execution are separate integration work.'))+
 links([['jev-news','Where narrative context comes from'],['jev-pipeline','Inspect the complete architecture'],['roadmap','Execution milestones']]),options),

 'jev-pipeline':page('The connected system','One record. Context across the whole workspace.',
 `<div class="jev-system-map"><div>X · GitHub · YouTube · Reddit · Websites · Instagram · Truth Social · News</div><i>↓</i><div><b>Native record</b><span>Source ID · original link · content · timestamps</span></div><i>↓</i><div><b>JEV News</b><span>Extraction → identity resolution → validation → narrative context</span></div><i>↓</i><div class="jev-system-destinations"><strong>Trackers & filters</strong><strong>Narrative views</strong><strong>JEV Trading</strong></div></div>`+
 note('Integration architecture. Collector availability and semantic enrichment are separate capabilities.')+
 s('source-layer','1. Collect once. Preserve the original.',p('Each adapter retains its native identity and captures the available content. Publication time and receipt time stay separate. Replies, quotes and reposts are independent context records; links to unavailable content remain unresolved.')+
 p('The existing feed remains responsive while enrichment runs asynchronously. Raw records are readable even when analysis is pending.'))+
 s('analysis-layer','2. Enrich without losing attribution.',p('The analysis layer builds an entity-and-event record: names, types, aliases, roles, claims, narrative candidates and supporting passages. Schema validation checks the shape; semantic validation checks whether the source supports the interpretation.')+
 details('Validation states',table(['State','Meaning'],[['Accepted','The relationship passes the configured evidence checks.'],['Probable','Supporting context with an unresolved qualification.'],['Insufficient','Essential evidence is missing.'],['Needs review','Attribution, identity or interpretation remains ambiguous.'],['Failed','Processing did not produce a usable result.']]))+
 p('Source content is data, including code snippets, captions and comments. Instructions embedded in it never become strategy permissions.'))+
 s('return-layer','3. Send the context back to its tracker.',p('Versioned enrichment attaches to the original event ID. GitHub keeps its repository, release and commit identities; YouTube keeps its video and channel; Reddit keeps its post, comment and community. Shared entity and narrative references enable cross-source exploration.')+
 `<div class="jev-principles">${card('FILTER','Find the event.','Use entity, role, event type and narrative fields in views and presets.')}${card('TRACE','Open the evidence.','Inspect the original record and supporting context behind an association.')}${card('UPDATE','Follow material changes.','Revisit enrichment when records change or new evidence affects the interpretation.')}</div>`)+
 s('cache-layer','4. Cache analysis. Keep market state fresh.',p('The integration design reuses unchanged analysis by source identity, content revision and analysis version. A changed source or extraction policy invalidates the relevant entry. Repeated distribution does not manufacture independent evidence.')+
 p('Market snapshots follow their own freshness policy. Before a trading decision, the system checks the observation time and required fields again. News metadata and executable prices never share a blanket cache lifetime.'))+
 s('trading-layer','5. Link the narrative to the exact asset.',p('The handoff joins a narrative to a token through explicit evidence, keyed by chain and contract. A direct source reference, an established project identity or a reviewed contextual match explains the association. A shared name alone does not.')+
 table(['News supplies','Trading adds'],[['Entities, roles and event context','Chain, contract and lifecycle'],['Source links and supporting records','Current liquidity, volume and flow'],['Narrative changes and freshness','Position, budget and risk constraints'],['Validation and unresolved context','Permitted next action and its reasons']])+
 p('Changes to either side can schedule a new evaluation. Independent checks can run concurrently; execution waits for the checks it requires. The decision record binds evidence, market snapshot, model version and strategy version.'))+
 links([['jev-news','Explore source enrichment'],['jev-trading','Explore decision labels'],['jev-research','Research references']]),options),

 'jev-research':page('Research & foundations','A clear line from research to product design.',
 p('Six references inform this architecture: entity extraction, semantic retrieval, connected context, evidence retrieval, adaptive workflows and confidence calibration. Each addresses a different part of the information-to-decision path.')+
 `<div class="jev-research-list">${research.map((r,i)=>`<article><div><span>0${i+1} / ${r.year}</span><a href="${r.url}" target="_blank" rel="noopener noreferrer">arXiv ↗</a></div><h2 id="${r.id}">${escape(r.title)}</h2><small>${escape(r.authors)}</small><h3>${escape(r.use)}</h3><p>${escape(r.detail)}</p><details><summary>What this reference does not establish</summary><p>${escape(r.boundary)}</p></details></article>`).join('')}</div>`+
 s('system-one','Jev’s decision interface.',p('TypeSafe describes Jev as a System One model that returns structured decisions. Its examples use Choice, Score and Noul questions. OMNIA’s architecture applies that idea to source evaluation and strategy inputs; structured output alone does not prove a decision correct.')+
 `<a class="jev-external" href="https://typesafe.ai/blog/introducing-system-one-models-and-jev" target="_blank" rel="noopener noreferrer">Read the TypeSafe introduction ↗</a>`+
 `<a class="jev-external" href="https://evals.typesafe.ai/" target="_blank" rel="noopener noreferrer">Explore decision types and workflows ↗</a>`)+
 note('These are design references, not claims that all cited methods are integrated into OMNIA. Paper results and provider benchmarks are not measurements of OMNIA latency, accuracy or trading performance.')+
 links([['jev','Return to the vision'],['jev-pipeline','Explore the architecture']]),options),
};
