// Editorial examples only. This module never runs inference or orders.
export const actions = [
 {id:'skip',label:'SKIP',title:'Protect the entry.',color:'#a4adb9',detail:'Keep the token outside the position when its setup fails the strategy, its identity is unresolved or essential evidence is missing.',inputs:'Source attribution · contract identity · fresh data · risk limits',transition:'New evidence can trigger another evaluation. Skipping one snapshot does not blacklist the token forever.'},
 {id:'buy',label:'BUY',title:'Enter with a reason.',color:'#c3f53c',detail:'Produce an entry candidate when narrative relevance, market activity and liquidity satisfy the configured entry conditions.',inputs:'Entry threshold · available liquidity · position budget · slippage limit',transition:'The execution layer must still validate the quote, permissions and limits. A BUY label is not a confirmed fill.'},
 {id:'hold',label:'HOLD',title:'Stay while the thesis holds.',color:'#b3d7ff',detail:'Retain an existing position while its context remains supportive and no protective or profit-taking rule takes precedence.',inputs:'Position state · narrative changes · flow · active exit rules',transition:'Each material update can change the evaluation. An empty wallet has no position to HOLD.'},
 {id:'moonbag',label:'HOLD MOONBAG',title:'Keep a bounded remainder.',color:'#c1adff',detail:'Retain the strategy-defined remainder after a partial exit, with its own exposure and exit conditions.',inputs:'Confirmed partial exits · remaining quantity · maximum exposure · exit rules',transition:'The remainder follows explicit limits. The label does not predict that the token will multiply in value.'},
 {id:'profit',label:'PROFIT',title:'Make the outcome explicit.',color:'#8fe1c3',detail:'Summarize a realized positive result once the order receipts and position accounting support it.',inputs:'Confirmed fills · cost basis · fees · realized proceeds',transition:'PROFIT is an outcome label, not another order instruction. An unrealized move is not realized profit.'},
 {id:'tp',label:'TP',title:'Exit in deliberate stages.',color:'#f0ce85',detail:'Apply take-profit stages TP1–TP5 to an existing position using its configured targets and quantities.',inputs:'Stage targets · filled quantity · executable quote · remaining balance',transition:'Advance only after the relevant fill is confirmed. Repeated observations must not execute the same stage twice.'},
 {id:'sl',label:'SL',title:'Respect the downside limit.',color:'#efa2ad',detail:'Request a protective exit when the stop condition or a configured risk rule is reached.',inputs:'Stop condition · position state · route availability · execution limits',transition:'A stop triggers an exit attempt; liquidity, slippage and network conditions still determine its actual fill.'},
];
export const trackers = [
 {id:'x',name:'X',icon:'x',event:'A post introduces a product. A reply adds a qualification.',native:'Post ID, author ID, original URL, publication time and reply / quote / repost references.',extraction:'Identify the product, speaker, stated change and supporting passage. Keep the reply and quoted author separate.',destination:'Topic and entity filters, narrative timeline, token-reference candidates.',example:'The source says “Orion launches today.” A quoted post contains a separate claim.'},
 {id:'github',name:'GitHub',icon:'github',event:'A repository publishes a release or changes implementation.',native:'Repository ID, commit SHA or release ID, author, tag, changed paths and available diff.',extraction:'Separate releases, implementation changes and documentation. Read available evidence before assigning impact.',destination:'Repository context, release filters, related project narratives.',example:'Release v2.0 adds an Orion integration. The repository relationship must be independently established.'},
 {id:'youtube',name:'YouTube',icon:'youtube',event:'A channel publishes a video, Short or live event.',native:'Video and channel IDs, title, description, publication / scheduled time and format.',extraction:'Attribute statements to available text. A transcript or media analysis is a separate input, with timestamps.',destination:'Channel and topic views, event timelines, linked entities.',example:'A title mentions Orion. Without a transcript, the spoken claims remain unknown.'},
 {id:'reddit',name:'Reddit',icon:'reddit',event:'A community opens a discussion and replies develop the story.',native:'Post / comment ID, subreddit, author, permalink, parent ID and times.',extraction:'Distinguish submission from replies, identify referenced entities and preserve disagreement and attribution.',destination:'Community filters, narrative evolution, original-source links.',example:'A community discusses Orion. Discussion alone does not make the announcement official.'},
 {id:'website',name:'Websites',event:'A newsroom, product page or article changes.',native:'Canonical URL, publisher, observed version, publication time when supplied and captured text.',extraction:'Identify the event, participants, roles and changed passage. Separate observation time from publication time.',destination:'Company context, article filters, versioned evidence.',example:'A product page changes its release date. The observation updates the existing event.'},
 {id:'instagram',name:'Instagram',icon:'instagram',event:'A profile publishes a caption, image or Reel.',native:'Media ID, account identity, permalink, caption, available media and timestamp.',extraction:'Analyze the captured caption. OCR and visual interpretation need separate evidence; a thumbnail is not a transcript.',destination:'Profile and topic views, referenced entities and social context.',example:'A caption names Orion. An image-only reference needs a separately captured visual analysis.'},
 {id:'truthsocial',name:'Truth Social',event:'An account publishes or amplifies a statement.',native:'Post and account IDs, original text, permalink, quoted / reposted context and time.',extraction:'Separate a new statement from amplification and preserve the original speaker.',destination:'Source views, entity filters, narrative spread.',example:'An account reposts the announcement. It adds distribution, not a second independent confirmation.'},
 {id:'news',name:'News',event:'A publisher reports an event or a follow-up.',native:'Article URL, publisher, headline, author when supplied, publication and receipt times.',extraction:'Extract who did what, to whom and where. Preserve reporting, quotations and uncertainty as distinct evidence.',destination:'News filters, entity relationships, developing narratives.',example:'A report quotes the product team. The quote belongs to that speaker, with the article as its source.'},
];
export const research = [
 {id:'gliner',title:'GLiNER',year:'2023',url:'https://arxiv.org/abs/2311.08526',authors:'Zaratiana et al.',use:'Extract entity spans with flexible types.',detail:'A reference for identifying people, products, organizations and other named entities without restricting the vocabulary to a small fixed catalogue.',boundary:'Extraction does not establish that two names refer to the same real-world entity.'},
 {id:'sbert',title:'Sentence-BERT',year:'2019',url:'https://arxiv.org/abs/1908.10084',authors:'Reimers & Gurevych',use:'Find related wording across different links.',detail:'A reference for semantic candidate retrieval: related reports can describe the same event with different wording and URLs.',boundary:'Similarity produces candidates. Identity, attribution and contract association still need evidence.'},
 {id:'graphrag',title:'From Local to Global: GraphRAG',year:'2024',url:'https://arxiv.org/abs/2404.16130',authors:'Edge et al.',use:'Connect entities, relationships and wider stories.',detail:'A reference for moving from source passages to an entity graph and grouped context, so a narrative can be explored beyond one isolated post.',boundary:'A generated graph interprets its source collection; it does not prove causality or endorsement.'},
 {id:'rag',title:'Retrieval-Augmented Generation',year:'2020',url:'https://arxiv.org/abs/2005.11401',authors:'Lewis et al.',use:'Retrieve the records behind an interpretation.',detail:'A reference for bringing external evidence into model context instead of relying only on model memory.',boundary:'Retrieved context can be incomplete or wrong. Source identity, timestamps and validation remain necessary.'},
 {id:'react',title:'ReAct',year:'2022',url:'https://arxiv.org/abs/2210.03629',authors:'Yao et al.',use:'Re-evaluate after new observations.',detail:'A reference for an observation–evaluation–action loop in which incoming evidence changes the next step.',boundary:'Its tasks do not validate OMNIA trading, execution speed or investment performance.'},
 {id:'calibration',title:'On Calibration of Modern Neural Networks',year:'2017',url:'https://arxiv.org/abs/1706.04599',authors:'Guo et al.',use:'Give confidence a measured meaning.',detail:'A reference for checking whether confidence matches observed correctness on held-out examples.',boundary:'An uncalibrated score is not an accuracy percentage; classification confidence is not a probability of profit.'},
];
