import {page,p,section as s,steps,table,shot,links,escape} from './helpers.js';
import {PRESETS} from '../product/terminal/catalog.js';
export const presetPages={
presets:page('Presets','Start with a preset, check its results and make it your own.',
steps(['Open a panel gear and select <strong>Browse presets</strong>.','Choose a preset. It fills the configuration without changing your live panel.','Review <strong>Preview</strong> and adjust the filters.','Select <strong>Apply</strong> to update this panel, or <strong>Add panel</strong> to create another.'])+shot('preset-library','Browse presets with Global, Robinhood, Musebook and My presets categories')+s('preview','Review before applying',p('Configuration is on the left and results are on the right on desktop. Apply replaces the current panel; Add panel creates another. On smaller screens, Preview appears below Config.')+shot('panel-settings','Panel configuration, preview results and Apply and Add panel buttons'))+s('saved','Save a reusable preset',p('Set a name and select <strong>Save preset</strong>. Find it under <strong>My presets</strong>. Saving does not apply the settings to the live panel. Selecting a saved preset makes a copy; editing that panel does not rewrite the saved preset.'))+s('includes','What is saved',p('A preset keeps the content type, coverage, companies, platforms, profiles, event types, keyword rules, search fields, media and sound settings. It saves the rules, not a frozen list of posts.'))+links([['recipes','Try a setup'],['preset-library','Browse the library'],['keyword-rules','Combine words']])),
'robinhood-coverage':page('Coverage','Choose where a panel looks for results.',
table(['Setting','What it searches'],[['Following','Content associated with the companies you follow.'],['All collected content','Collected content across the dataset, including posts without a company association.'],['Selected companies','Content associated with the companies checked in panel settings. This narrows the coverage.']])+s('global','Global and Robinhood presets',p('Global presets do not require the word Robinhood or a token link. A post about a mascot can match from any collected source. Robinhood presets add the words or relationships shown in their configuration.'))+s('network','Network and subject are different',p('A Robinhood Chain token can link to a Pepe post that never mentions Robinhood. A token relationship filter can include that post; a keyword rule requiring Robinhood would exclude it.'))+links([['preset-token-links','Require a token link'],['preset-limits','Understand coverage limits']])),
'keyword-rules':page('Keyword rules','Choose words to include and words to leave out.',
table(['Field','Example','Result'],[['Topic · any word','robinhood, musebook','At least one topic term must match.'],['All words','coin, mascot','Both words must match.'],['Any word','coin, mascot','Either word can match.'],['Exact phrases','new mascot','The words must appear together in that order.'],['Exclude words','giveaway, airdrop','Either match removes the result.']])+shot('keyword-rules','Keyword fields with coin and mascot in Any word')+s('combine','Combine the fields',p('Separate terms with commas. Every nonempty positive field must pass. Exclude words takes priority. For example: Topic = robinhood and Any word = coin, mascot requires Robinhood plus either coin or mascot.'))+s('literal','Words are matched literally',p('Matching ignores letter case. <strong>coin</strong>, <strong>coins</strong>, <strong>$COIN</strong> and <strong>Coinbase</strong> are different terms. Add each version you want. The filter does not translate text, guess synonyms or read words inside an image.'))+table(['Text','All words: coin, mascot'],[['Meet our mascot coin.','Matches'],['Our mascot at Coinbase.','Does not match coin'],['Our mascot joins $COIN.','Does not match coin'],['New mascot.','Does not match coin']])+links([['search-fields','Choose where words can match'],['recipes','See working configurations']])),
'search-fields':page('Search fields','Choose which parts of a record can match your keywords.',
table(['Field','Searches'],[['Post text','Available post text, or the body/title when full text is missing.'],['Quoted and replied-to posts','The retained text inside quotes and replies.'],['Author name and handle','The available author name, handle and source label.'],['Token name, symbol and description','Token metadata in a Tokens panel.']])+s('scope','Same field or several fields',p('<strong>Same content field</strong> requires the positive rules to match inside one selected field. <strong>Selected content fields</strong> allows terms to be spread across those fields.')+p('Example: a post says coin and its quote says mascot. To require both, select post text and context, then choose Selected content fields. An exact phrase still has to appear inside one field. Exclusions check every selected field.'))+s('media','Media filters are separate',p('<strong>Required media</strong> filters for an image, video or either. <strong>Media</strong> changes how previews display: Compact, Full or Hidden. Neither setting reads text inside images or transcribes video.'))+links([['keyword-rules','Keyword examples']])),
'people-topics':page('People & topics','Follow someone’s posts, mentions of them, or both.',
s('authors','Only posts from selected profiles',p('Choose the profiles under <strong>Profiles</strong>. Other authors are excluded, even if they mention the same person.'))+s('mentions','Find mentions from other authors',p('Leave Profiles unrestricted. Choose <strong>All collected content</strong> and add the person or topic to your keywords. Search <strong>Post text</strong> for mentions. Add <strong>Author name and handle</strong> to also match the author.'))+s('vlad','Example: Vlad',p('The Vlad preset searches vlad tenev, vladtenev and vladimir tenev in post text and author fields. It can include both posts by a matching author and mentions by other people. These are text matches; check the profile link when identity matters.'))+s('mascot','Example: Mascot Any',p('Mascot Any matches the word mascot. A photo of a mascot without that word in the selected text will not match. Add words, profiles or media requirements to fit your research.'))),
'preset-token-links':page('Token origins','Find posts and pages linked from token metadata.',
table(['Token relationship','Includes'],[['Any collected content','No token link is required.'],['Linked by Robinhood tokens','Records with at least one indexed token association.'],['Linked by 2+ Robinhood tokens','Records with at least two indexed token associations.']])+s('origin','What an origin means',p('OMNIA matches supported source URLs from token metadata to known posts or pages. A profile URL is not automatically a link to a particular post. Similar names and images are not direct source links.'))+s('read','Use the relationship',steps(['Choose <strong>Latest news</strong> for recent matching content or <strong>Top today</strong> for 24-hour link activity.','Choose the required <strong>Token relationship</strong>.','Add keywords or companies only if you want a narrower result.','Open the source and inspect the linked token separately.']))+p('A token using a source link does not prove the author created or approved that token. If a link cannot be recovered, its source card may be missing.')+links([['preset-ranking','How Top today ranks sources']])),
'preset-library':page('Preset library','Use these starting rules as-is or edit them.',
shot('preset-library','The current preset library')+table(['Preset','Starting rule'],PRESETS.map(x=>[escape(x.name),escape(x.description)]))+s('edit','Check the actual rules',p('Choose a card to inspect its keywords, fields and coverage. All presets are optional. The library does not add panels automatically, and library changes do not overwrite panels you already saved.'))+s('ecosystem','Ecosystem presets',p('Ecosystem Robinhood and Musebook use the vocabulary listed in settings. Meme Robinhood combines ecosystem terms with meme terms. Muse requires Muse vocabulary plus AI, Meta or agent context. These presets search mentions; they do not establish affiliation or complete coverage of a network.'))+links([['recipes','Customize a preset'],['people-topics','Separate authors from mentions']])),
recipes:page('Setup examples','Build a panel around the way you research.',
table(['Setup','Choose these settings'],[['Coin or mascot, globally','Latest news · All collected content · Any word: coin, mascot'],['Coin and mascot together','All collected content · All words: coin, mascot · Post text'],['Reddit Hot for NVIDIA','Reddit Hot preset · Companies: NVIDIA'],['Reddit Rising across companies','Reddit Rising preset · All collected content'],['YouTube for ten companies','Latest news · Platforms: YouTube · Select your ten companies'],['Only one author','Select that profile under Profiles; remove unrelated keyword rules'],['Vlad posts and mentions','Vlad preset · Keep Profiles unrestricted'],['Meme activity around Robinhood','Meme Robinhood preset · Review its topic and meme vocabulary'],['Posts with pictures','Required media: Image'],['Repeated token origins','Top today · Linked by 2+ Robinhood tokens']])+s('preview','Check before applying',p('Preview uses the current configuration. If the results are too broad, add a company, profile or exclusion. If no results appear, remove one restriction at a time.')+p('For a custom setup, start with one rule. Add more once the preview shows the kind of content you want.'))+links([['preset-limits','Fix an empty preview'],['search-fields','Match words across a quote']])),
'preset-limits':page('Coverage & limits','Understand what a matching result does—and does not—mean.',
s('data','Collected content',p('Global panels search retained records across the server dataset. Coverage varies by source and by what OMNIA has collected. Missing bodies, unavailable media and unresolved links can affect results.'))+s('empty','When a preview is empty',steps(['Choose <strong>All collected content</strong> if you do not want Following to narrow results.','Check selected companies and profiles.','Remove token relationship or media requirements temporarily.','Check spelling and word variants such as coin, coins and $COIN.','Select context fields if your words appear inside a quote or reply.','Clear legacy text filters. In Tokens, use <strong>Load more</strong>.']))+s('error','When a preview fails to load',p('A loading error is different from no matches. Retry after a moment, check your connection and reopen the panel. Changing a keyword cannot fix an unavailable source or service.'))+s('not-supported','What keyword rules do not do',p('They do not perform visual mascot recognition, OCR, video transcription, semantic story grouping or automatic synonym expansion. A match is not a prediction of a token’s performance.'))),
};
