import {page,p,section as s,steps,table,shot,links} from './helpers.js';
export const researchPages={
companies:page('Companies','Find a company or fund and choose what to follow.',
shot('companies','Company catalog with search, categories and tracking controls')+steps(['Open <strong>Companies</strong>. Search by name or ticker.','Choose All, Companies or Funds. Use Following to show your current selection.','Open a company logo to inspect its activity.','Use Track or the tracking options to choose feed and Telegram sources.'])+s('bulk','Track a group',p('Track all and Stop tracking all apply to the visible group. Check your search and category before using them. Feed and Telegram have separate selections.'))+links([['following','Manage your selection'],['company-pages','Read company activity']])),
'company-pages':page('Company pages','Review a company’s activity and available sources.',
s('activity','Find a record',steps(['Open a company from the catalog.','Choose All activity or a source tab.','Use Profiles and search to narrow the records.','Open an item and follow its original source when you need more context.']))+s('counts','Read the counts',p('Counts describe the records available in the product. They do not measure every mention on the internet. A company can appear in the catalog before every platform has collected records.'))+s('archive','Go deeper',p('Use Archive for the company’s retained records and relationship graph. A company logo, mapped profile and individual post represent different things.'))+links([['archive','Explore the Archive'],['source-records','Understand a record']])),
archive:page('Archive','Explore companies, their sources and retained records.',
s('find','Explore a company',p('Find a company or ticker in the asset index. Its archive brings Activity, Sources, Relationships and Narratives into one workspace.'))+s('activity','Search retained activity',p('Search posts, source names or keywords across the retained records. Filter by platform, activity type and an inclusive UTC date range. Load more keeps those filters. Refresh retrieves the latest available records.')+p('Posts show their captured text once, with the author, publication or received time, and original link. Open a record for the full content. Quotes and replies expand in place; nearby GitHub commits from the same repository are grouped without removing individual records.'))+s('sources','Inspect a source',p('Search the source registry and filter by platform or status. Select a row to inspect its profile, capture date, metrics and original link. The details open directly on desktop and mobile.')+p('Profile capture, publication and collector checks are separate. Expand Collection health for the latest check, last success and reported issues. A shared collector check does not confirm every profile. Missing telemetry stays Not reported.'))+s('relationships','Follow the connections',p('Relationships uses the activity records loaded for this company. Filter sources by platform or name, show more sources, zoom or reset the network. Select a node for its evidence, or switch to List for keyboard and compact-screen navigation. Counts distinguish the displayed subset from all matching sources.')+p('A mapped relationship does not automatically establish ownership or endorsement. Source-to-record links require an exact identity match.'))+s('narratives','Inspect research',p('Filter reviewed findings by topic. Each card keeps its description, repository and original evidence together. Research coverage and methodology expand separately; company-wide source totals are not counts of evidence for an individual finding.'))+links([['time-and-evidence','Read times and evidence'],['company-pages','Return to company activity']])),
following:page('Following','Choose companies and sources separately for the feed and Telegram.',
shot('following','Following controls for companies and delivery destinations')+steps(['Open <strong>Following</strong>.','Open a company’s tracking options.','Choose the controls for <strong>My Feed</strong> or <strong>Telegram</strong>.','Select the platforms and profiles you want for that destination.'])+s('separate','Two independent selections',p('You can keep a broad feed and a smaller Telegram selection. A company can send Telegram alerts without every source being enabled in your feed.'))+s('save','Check that settings saved',p('Following settings synchronize with your eligible account. If saving fails, reload the current settings before trying again. Telegram also needs a connected destination.'))+links([['telegram','Connect the destination'],['robinhood-coverage','Use Following in a panel']])),
'source-records':page('Read a record','Identify the author, company, content and original source.',
table(['Element','How to read it'],[['Company logo and ticker','The stock context associated with the record.'],['Author name and handle','Who posted or performed the action. Open the profile to inspect it.'],['Followers','The count supplied with the available profile data, when present.'],['Action','Post, reply, quote, repost, deletion or another recorded event.'],['Nested post','The quoted or replied-to content and its own author.'],['Time','Publication or received/observed time, as labelled.'],['Original source','The external post or page.']])+s('open','Open the details',p('Select the content to open its record when a detail view is available. The original-source link opens the external page. Quotes and replies start compact in the feed. Expand the context to read the full captured text, media and original link.'))+s('media','Missing text and media',p('OMNIA shows the content it has. An unavailable image or incomplete source does not mean the post had no media or no additional text. Open the original link if it remains accessible.'))+links([['x','Understand social actions'],['time-and-evidence','Understand time labels']])),
'time-and-evidence':page('Time & evidence','Know when something was published and when OMNIA found it.',
table(['Label','Meaning'],[['Published','The time reported by the source.'],['Received / Observed','When the record reached OMNIA or was observed.'],['Snapshot','The reference time of an archive view.'],['Indexed','The record is available for search in the dataset.'],['Archived','The product identifies retained source material for the record.']])+s('old','An old post can arrive now',p('Collection time does not turn an old post into a new publication. Top today uses recent token-link activity, so its source post may be older than the 24-hour window.'))+s('timezone','Time zones',p('Feed and archive timestamps use the labels shown in the interface, commonly UTC. Telegram quiet hours use the time zone selected in Telegram settings.'))),
deduplication:page('Repeated records','Understand why similar items can appear more than once.',
table(['Example','What it means'],[['Two collectors observe the same native post','Repeated collection should resolve to the same source identity.'],['A reply and its quoted context repeat some text','They may be different actions with shared context.'],['A post is later deleted or pinned','The action is different from the original publication.'],['Several tokens use one source link','Several associations can point to one source.'],['Two contracts use the same name','They are still different token contracts.']])+s('check','Check before treating it as a duplicate',p('Compare the original URL, action, author and contract address. Similar text alone does not establish a duplicate. If the same source and action repeat unexpectedly, keep those details when reporting the issue.'))),
};

researchPages['following'].updated='2026-09-25';
researchPages['archive'].updated='2026-09-25';
