import {page,p,section as s,steps,table,shot,links} from './helpers.js';
import {eventCategories,typeLabel} from '../product/terminal/categories.js';
const platforms=[['x','X'],['reddit','Reddit'],['youtube','YouTube'],['github','GitHub'],['instagram','Instagram'],['truthsocial','Truth Social'],['news','News'],['web','Website'],['filings','Filings']].map(([id,label])=>({id,label}));
export const sourcePages={
trackers:page('Source trackers','Open one source at a time from the tabs above My Feed.',
table(['Tracker','Content'],[['X','Posts, replies, quotes, reposts and observed changes.'],['Reddit','Topics, ranking states and captured community changes.'],['YouTube','Videos and captured changes from mapped channels.'],['Website','Mapped websites, newsrooms and news sources.'],['GitHub','Repository activity, commits and releases.'],['Instagram','Collected records related to stocks.'],['Truth Social','Collected posts and available context.']])+s('tabs','Choose your shortcuts',p('Use the tracker menu to choose which shortcuts appear. Removing a shortcut does not delete records or your tracking preferences.'))+s('records','Different record types',p('Some trackers offer <strong>Posts</strong>, <strong>Changes</strong>, <strong>Profiles</strong>, <strong>Links</strong> and <strong>All records</strong>. A profile record describes an account; a link record may point to content OMNIA has not recovered.'))+links([['event-types','Event types'],['preset-limits','Coverage limits']])),
'event-types':page('Event types','Limit a panel to the actions you want to see.',
steps(['Open a panel gear.','Expand <strong>Event types</strong>.','Choose types under the relevant platform, then check Preview.'])+table(['Category','Built-in choices'],eventCategories([],platforms).map(g=>[g.label,g.types.map(typeLabel).join(', ')]))+s('more','Additional types',p('The menu can also include event types found in collected records. Seeing a type in the menu does not mean that source has produced a matching event recently. Reddit Hot and Rising are ranking filters, separate from the post itself.'))+links([['source-changes','Filter profile changes'],['x','Read X actions'],['reddit','Reddit rankings']])),
x:page('X Tracker','Read posts with their authors, media and available context.',
s('read','Read the post',p('The main author is the account that performed the action. A quote or reply can contain another author below it. Profile links open the matching account. Follower counts appear when supplied by the source and may differ from today’s count.'))+table(['Action','Meaning'],[['Post','A standalone post.'],['Replied','A reply, with the replied-to post when available.'],['Quoted','A post that includes another post as context.'],['Reposted','Another account’s post shared by the main author.'],['Deleted','An observed deletion. Retained content can still be shown; the feed marks it red.'],['Pinned / Unpinned','An observed change to the account’s pinned post.']])+s('company','Company and author are different',p('The stock logo identifies the associated company context. It does not mean the author works for that company. The feed can include third-party mentions as well as company profiles.'))+s('missing','Missing context or media',p('Only available content can be displayed. A deleted or blocked source may no longer open. A profile change is not the same event as a newly published post.'))+links([['people-topics','Watch authors or mentions'],['source-records','Read times and source links']])),
reddit:page('Reddit Tracker','Follow topics from mapped Reddit communities.',
table(['Ranking','Meaning'],[['New','Recently submitted topics.'],['Hot','Topics ranked as hot by the source.'],['Rising','Topics appearing in the rising listing.'],['Top','Top-ranked topics for the source window.']])+s('setup','Choose a ranking',p('Start with Reddit Rising or Reddit Hot in the preset library. Select a company to narrow it, or keep All collected content for a broader view. Reddit ranking choices for Telegram are separate from your feed.'))+s('changes','Posts and ranking changes',p('A topic can move between listings. A ranking-change signal describes a transition, not a new submission. The company topic feed focuses on submissions; a comment is not automatically a new company news item.'))+s('community','Check the community',p('A mapped subreddit is relevant to a company context. It does not necessarily belong to that company. Open the original thread for the discussion.'))),
youtube:page('YouTube Tracker','Find videos from mapped company and topic channels.',
s('watch','Open a video',steps(['Select <strong>YouTube Tracker</strong>.','Choose companies or profiles where the view offers those filters.','Open a video or use its available player.','Follow the original link for the full YouTube page.']))+s('content','What a record contains',p('Records can include the video title, description, channel, publication time and thumbnail. Video, Short and Live stream labels depend on the available metadata. Some views load the player only when you open a record.'))+s('dates','Publication and discovery',p('Received shows when OMNIA discovered a video, not when it was published. When a channel feed is unavailable, public channel pages can provide recent videos. Older videos may appear during recovery; records without a verified publication date are not sent as new-publication alerts. Collected videos are not a complete channel history.'))+s('missing','When playback is unavailable',p('Embedding restrictions, removed videos and missing metadata can prevent playback. Try the original source. Keyword filters search the available text; they do not search a spoken transcript.'))+links([['recipes','Track YouTube for selected companies']])),
website:page('Website Tracker','Follow mapped websites, newsrooms and public news.',
s('sources','What is covered',p('Coverage comes from the sources mapped for each company: official pages, newsrooms, investor resources and external news where available. A company in the catalog does not mean every page on its website is monitored.'))+s('read','Read a web record',p('Check the publisher and original URL. An official announcement and an external article are different sources. A detected page update is not necessarily a newly published article.'))+s('time','Check the date',p('Some pages provide a publication time; others only provide a date or an observed time. Use the displayed label rather than assuming every update was just published.'))+links([['company-pages','Inspect company sources'],['time-and-evidence','Understand timestamps']])),
github:page('GitHub Tracker','Follow development activity from mapped repositories.',
table(['Type','Meaning'],[['Commit','A recorded commit or push event.'],['Release','A published release record.'],['New repository','A newly observed repository creation event.']])+s('inspect','Inspect the change',p('Read the repository name, event title and time. Open the original GitHub link for the diff, release notes or repository. A commit message is not proof that a feature is deployed.'))+s('groups','Commit groups',p('In the feed, commits from the same repository are grouped within 15-minute windows. Expand a group to inspect every original record and source link. Releases stay separate. Grouping only changes the presentation of loaded records.'))+s('filter','Keep the feed useful',p('Choose companies and repositories or profiles where available. Use Event types to keep releases and hide commits if you want fewer updates.'))),
instagram:page('Instagram','Read collected Instagram content related to stocks.',
s('coverage','Stock-related records',p('The Instagram tracker requests records with stock associations. The company logo and ticker show the associated stock context. A mention of a company is not proof of employment or endorsement.'))+s('views','Choose a record type',p('Use Posts for content, Changes for observed updates, Profiles for account records or Links for discovered URLs. Select Refresh to request the latest page.'))+s('media','Photos and video',p('Available images, video and captions appear in the record. Missing or expired media may require opening the original source. The tracker is not a complete archive of every Instagram account.'))),
truthsocial:page('Truth Social','Review collected Truth Social posts and source links.',
s('read','Open a record',p('Select Truth Social in the feed tabs. Choose Posts, Changes, Profiles, Links or All records as needed. Read the author, text and time, then open Original source for context.'))+s('coverage','Available content',p('A discovered URL can appear before its post content is recovered. Reply or repost context appears only when retained. The tracker does not establish complete coverage of every account or action.'))+s('alerts','Telegram delivery',p('A record in the tracker is not a Telegram delivery receipt. Check your Telegram selection and connection separately.'))+links([['telegram','Configure Telegram']])),
};

for(const [id,title,text] of [
 ['reddit','Community changes','Use Reddit community changes in Browse presets, or select specific changes under Event types → Reddit. The current profile campaign captures names, descriptions, photos, banners and supported settings. These records use observation time. The first capture establishes a baseline; later differences include Before and After. Rankings remain separate from profile changes.'],
 ['youtube','Channel changes','Use YouTube channel changes in Browse presets, or select a specific change under Event types → YouTube. Channel profiles and uploads are collected separately. Names, descriptions, photos and supported banners produce changes only after two successful comparable captures. Check collection status for the source.'],
 ['github','Repository changes','Use Repository updates in Browse presets. Select README changed, Releases changed, Description changed or Settings changed to narrow the observations. A release-window difference is separate from a published release event.'],
]) {
 sourcePages[id].body += s('profile-changes',title,p(text))+links([['source-changes','Read and filter changes']]);
 sourcePages[id].updated='2026-09-25';
}
