import {intelligencePages} from './intelligence.js';
import {page,p,section as s,steps,table,links} from './helpers.js';
const screenshot=(file,alt)=>`<figure class="doc-shot"><a href="/assets/docs/${file}.png" data-doc-image aria-label="Enlarge: ${alt}"><span class="doc-shot-frame" style="width:1265px;--shot-native-width:1265px;aspect-ratio:1265/712"><img src="/assets/docs/${file}.png" alt="${alt}" loading="lazy" width="1265" height="712" style="width:100%"></span></a></figure>`;
export const updatePages={
...intelligencePages,
'musebook':page('Musebook preset','Follow the conversation in a dedicated panel.',
steps(['Open a panel gear, then <strong>Browse presets</strong>.','Choose the <strong>Musebook</strong> category and the <strong>Musebook</strong> preset.','Review the results beside Config. Adjust the filters if needed.','Select <strong>Add panel</strong> to keep your other panels, or <strong>Apply</strong> to replace this one.'])+
screenshot('musebook-preview','Musebook selected in Panel settings with a matching Musepad post in Preview')+
s('choose','Choose the right starting point',table(['Preset','Rule'],[['Musebook','Matches listed Musebook, Musegram, Musepad and Muse references in post text or author fields.'],['Muse','Requires Muse vocabulary together with AI, Meta or agent context.'],['Muse Launches','Requires ecosystem vocabulary together with launch activity terms.']]))+
s('adjust','Make it fit your setup',p('Keep All collected content to search beyond the companies you follow. Add a platform, profile or exclusion to narrow the results. Each additional filter can remove matches.')+screenshot('musebook-filters','Musebook keyword fields and matching source preview'))+
s('scope','What a match means',p('This is a keyword preset over collected content. It does not identify every project, verify a token, or predict which trend will grow. The Musebook preset also includes @muse and muse.ai, so some results are broader than Musebook itself. Open the source before drawing a connection.'))+links([['keyword-rules','Combine filters'],['integrations','Send panel alerts']])),
'integrations':page('Discord & Telegram destinations','Send a panel’s matching news to your own channel or group.',
links([['discord','Connect Discord'],['telegram-custom','Connect your Telegram bot'],['panel-delivery','Send a panel'],['delivery-status','Check delivery']])+p('Connect supported destinations from your full-access workspace, then choose which panels send alerts. Destinations and delivery capacity are part of the holder experience.')+
s('choose','Choose your Telegram setup',table(['Option','Selection'],[['OMNIA bot for panels','Link Telegram in Settings → Alerts → Following alerts, then select Add OMNIA bot in Panel alerts. Choose it in each panel. No personal bot token needed.'],['Your own Telegram bot','Connect a group/channel using your bot token and destination ID.'],['Existing Following alerts','Keep using company selections and schedule. These settings remain unchanged when you add panel alerts.']]))+s('connect','Connect once',steps(['Sign in and open <strong>Settings → Alerts → Panel alerts</strong>.','Name the destination and choose Discord or Telegram.','For Discord, paste the channel webhook URL. For Telegram, paste your bot token and group or channel ID.','Select <strong>Connect destination</strong>, then use <strong>Test</strong> to send a test message.']))+
table(['Platform','What you need'],[['OMNIA bot','Your confirmed Telegram account connection. No token or chat ID to copy.'],['Discord','A webhook created for the destination channel.'],['Your Telegram bot','A bot token and a group/channel ID, or a public @channel. The bot must be allowed to post there.']])+
s('panel','Choose what gets sent',steps(['Open the gear on a <strong>Latest news</strong> panel. Choose a preset or set your own filters.','Keep <strong>Token relationship → Any collected content</strong>.','Open <strong>Discord / Telegram → Choose destinations</strong> and select your saved destinations.','Select <strong>Save alerts</strong>. Apply later panel changes to update its delivery filters.']))+
p('Saved delivery runs on the server, including when your browser is closed. Top today, Tokens and token-relationship filters are not supported for this delivery mode yet. Adding a panel alone does not enable delivery.')+
s('manage','Manage destinations',table(['Control','Result'],[['Test','Sends one connection test. Wait a minute before testing that destination again.'],['Pause','Stops new delivery to that destination. Queued alerts remain for resumption.'],['Remove','Deletes the saved destination.'],['Clear panel selections + Save alerts','Stops delivery for that panel.']]))+
s('limits','Access and future holder tiers',p('Holder levels expand destination capacity. The workspace shows your active allowance; paused destinations still count. Holder allowances open with the token launch.')+table(['Holder level','Destinations'],[['Tier 1','100,000 tokens / 7 destinations'],['Tier 2','500,000 tokens / 20 destinations'],['Tier 3','1,000,000 tokens / 50 destinations'],['Tier 4','5,000,000 tokens / 500 destinations']])+p('Token verification is not active yet. When enabled, holder limits will be shared across Discord and Telegram and checked by the server.'))+
s('delivery','When a message is missing',p('First send a test. Then check that the destination is enabled, the panel delivery was saved, and a new event matches all filters. A connection test does not prove every source is collecting. Provider limits can delay messages. An unconfirmed status means delivery could not be verified; check the destination before trying again.'))+
s('secrets','Keep credentials private',p('Credentials are encrypted on the server and are not returned in the destination list. Never share screenshots containing a webhook URL or bot token. If a credential is exposed, replace it with its provider.'))+links([['telegram','OMNIA bot alerts'],['presets','Panel presets']])),
'live-feed':page('Live updates & previews','New matching records update your open panels.',
s('live','How updates arrive',p('The feed starts with a recent set of records. The server then sends changes over a live connection, and each panel checks them against its filters. The browser does not reload the full archive for each post.'))+
s('preview','Preview your rules',p('Preview requests up to 20 matching results. Built-in presets reuse prepared results where available. Custom combinations are searched when needed; uncommon or broad queries can take longer. A cached result may appear while newer results load.'))+
s('capacity','When the service is busy',p('Searches and live connections have server-side limits. If a request exceeds its allowance, OMNIA returns a retry response rather than starting unlimited work. Live updates use a separate connection limit.'))+
s('disconnect','If the connection drops',p('The app reconnects and requests missed changes where they are still available. After a long interruption it may need to refresh its starting data. If a panel looks old, check filters and compare Published with Received time.'))+
s('timing','What affects timing',p('A live connection starts helping after the source has been collected. Delays at the source, ingestion, network or external delivery provider can still affect arrival. No fixed end-to-end delay is guaranteed.'))+links([['preset-limits','Check preview results'],['time-and-evidence','Read event times'],['integrations','External delivery']])),
'whats-new':page('What’s new','A clearer workspace. A stronger holder experience.',
s('holder-levels','Holders · the next chapter',p('Four holder levels bring the complete released website from 100,000 $OMNIA, with greater capacity and earlier betas at 500,000, 1,000,000 and 5,000,000. Developer API eligibility starts at 1,000,000 $OMNIA, with personal keys coming in a later release.')+links([['holders','Compare holder levels'],['developer-api','Developer API']]))+
s('new-docs','Inside JEV',p('A dedicated JEV collection connects the vision, JEV News, JEV Trading, the complete information flow and the research behind the architecture. Explore source-specific metadata, seven decision labels and the parameters behind each evaluation, with original OMNIA artwork.')+links([['jev','Explore JEV'],['jev-news','JEV News'],['jev-trading','JEV Trading'],['roadmap','Follow the roadmap']]))+
s('custom-source-rollout','Custom sources · controlled rollout',p('Custom source subscriptions are being prepared for a staged beta, adding your own Reddit communities, GitHub repositories and YouTube channels. Separate collection status, private source activity, before/after evidence and a Custom sources panel keep the workflow clear. This rollout remains disabled in production until validation is complete.')+links([['custom-sources','Source allowances and setup'],['source-changes','New change signals']]))+
table(['Update','What changed'],[['Panel delivery','Connect your own Discord webhook or Telegram bot and select destinations per news panel.'],['Destination tiers','A compact tier indicator and usage bar replace the token threshold list.'],['Live feed','New records and changes update panels without rebuilding the full archive.'],['Preset previews','Up to 20 matching results, with prepared results for built-in presets.'],['Musebook','Separate Musebook, Muse and Muse Launches presets with editable rules.'],['Source cards','Primary author, handle and available follower count appear above source details. Deleted events are marked red.'],['Top today','A rolling 24-hour window of token-link activity, not a midnight reset.']])+
links([['integrations','Set up destinations'],['musebook','Use Musebook'],['live-feed','Understand live updates'],['preset-ranking','Read Top today']]))
};

updatePages['integrations'].updated='2026-09-25';
updatePages['whats-new'].updated='2026-09-25';
