import {page,p,section as s,steps,table,shot,links} from './helpers.js';
export const workspacePages={
overview:page('Welcome to OMNIA','See the signal. Follow the source. Build your edge.',
p('OMNIA brings collected news, social activity and token-linked sources into one research workspace. Shape your own feeds, follow the stories that matter and move from a signal to its original source.')+shot('workspace','OMNIA workspace with Latest news, Top today and Tokens')+links([['product-tour','Build your workspace'],['holders','Explore holder access'],['presets','Discover presets'],['jev','Meet JEV · coming soon']])+s('workspace','Your core views',table(['Panel','What you see'],[['Latest news','Recent posts and events that match your settings.'],['Top today','Source posts ranked by token-link activity in the last 24 hours.'],['Tokens','Discovered tokens, stock pairings and source links.']]))+p('These guides explain the product interface and user workflows. Global searches cover content collected by OMNIA, not every post on the internet.')),
'product-tour':page('Get started','Build your first feed in a few steps.',
steps(['Select <strong>Open OMNIA</strong>. The Standard workspace contains Latest news, Top today and Tokens.','Open the gear on <strong>Latest news</strong>. Select <strong>Browse presets</strong>.','Choose <strong>COIN + MASCOT ANY</strong>, or another preset that fits your setup.','Check <strong>Preview</strong>. Change the filters if the results are too broad.','Select <strong>Add panel</strong> to keep the original panels and add your new view.'])+shot('preset-library','Preset library inside Panel settings')+s('next','Make it yours',p('Use the arrows to reorder panels. Open a panel in a separate window for a second monitor. Choose sounds only for the panels you want to hear.')+links([['windows-alerts','Move panels and open windows'],['sounds','Set up sounds'],['companies','Follow companies']]))+s('save','Keep your setup',p('Sign in to your eligible account to save supported preferences and connect delivery destinations. See Holders for holder levels. Browser-specific settings and custom sounds may need to be added again on another device.'))),
'my-feed':page('My Feed','Choose what you want to follow and keep separate views beside each other.',
shot('feed-views','Recent, Top, Tokens and source tracker tabs above the feed')+s('views','Choose a view',table(['View','Use it for'],[['Recent','Open your workspace of panels.'],['Top','Read sources with token-link activity in the last 24 hours.'],['Tokens','Browse token records and their links.'],['Trackers','Open one source, such as X or Reddit.']]))+s('presets','Set up each panel',p('Each panel has its own content, coverage, filters and sound. Changing one panel does not replace the other panels. Open its gear to edit it.')+links([['presets','Create a panel'],['panel-delivery','Send this panel to Discord or Telegram'],['preset-ranking','Understand Top today']]))+s('following','Choose coverage',p('<strong>Following</strong> uses your selected companies. <strong>All collected content</strong> includes collected posts without a company association. Selecting specific companies narrows the panel to those companies.'))),
workspaces:page('Workspaces','Save different panel layouts for different ways of working.',
shot('workspaces','Workspace selector and Rename, Save as new, Add standard and Delete workspace controls')+steps(['Open the gear beside the <strong>Workspace</strong> selector.','Enter a name. Use <strong>Rename</strong> for the current workspace or <strong>Save as new</strong> for a copy.','Use <strong>Add standard</strong> to create a fresh three-panel layout.','Switch layouts with the <strong>Workspace</strong> selector.'])+s('copies','What a copy includes',p('Save as new copies the current panels and their settings into a separate workspace. Later edits apply to the selected workspace. A saved panel preset is different: it is a reusable configuration for one panel.'))+s('remove','Remove a workspace',p('<strong>Delete workspace</strong> removes its saved layout. It does not delete collected posts or tokens. The last remaining workspace cannot be deleted.'))+links([['presets','Save a panel preset'],['access','Local and account settings']])),
'windows-alerts':page('Panels & windows','Arrange panels in the workspace or move them to another window.',
shot('panel-controls','Panel header with move left, move right, open in window, configure and remove controls')+table(['Control','Action'],[['← / →','Move the panel left or right.'],['↗ Open in window','Open a separate view. The panel leaves the main grid once that view is active.'],['↙ Return to workspace','Put the detached panel back in its saved position.'],['Gear','Edit the panel and preview its results.'],['× Remove','Remove this panel configuration. Collected records stay available.']])+s('return','Bring a panel back',p('Use <strong>Return to workspace</strong> in the separate window. Closing that window also returns the panel. After a browser crash, recovery can take up to two minutes.'))+s('blocked','If the window does not open',p('Allow popups for OMNIA in your browser. Some embedded browsers open a tab instead of a separate window.'))+links([['sounds','Choose a sound'],['workspaces','Save the layout']])),
'preset-ranking':page('Top today','Find sources that tokens linked to during the last 24 hours.',
s('top','How the list is ordered',p('Top today ranks recovered source URLs by the number of associated tokens in the rolling 24-hour window. More recent link activity breaks ties. Filters are applied before the first 20 results are selected.')+p('The window keeps moving. It does not reset at midnight. A source post can be older than 24 hours if tokens linked to it during the window.'))+s('source','Read the source, not a token card',p('Top today shows the post or page behind a link. Open Tokens to inspect individual tokens. Several URLs about the same story can appear separately; this is not a ranking of all social engagement or price movement.'))+s('missing','Why a source may be missing',p('A token link may exist before OMNIA retrieves the post. Deleted posts, blocked pages and missing content can prevent a card from appearing. Your company, platform and keyword filters can also remove it.'))+links([['preset-token-links','Understand token origins'],['tokens','Read token cards']])),
tokens:page('Tokens','Inspect discovered tokens and the links attached to them.',
shot('tokens','Token cards showing names, contract addresses and stock pairings')+s('card','Read a token card',table(['Field','Meaning'],[['Name and symbol','The token identity supplied in the collected metadata. Names can be reused.'],['Contract address','The address to check on the matching network.'],['Paired with','The stock context associated with the token in the feed.'],['Time','The creation time when available.'],['Explorer / Market','Links to external contract and market information.'],['X / Website / Telegram','Links provided with that token when available.']]))+s('pairing','Understand the stock pairing',p('A stock pairing does not mean the company issued or endorsed the token. Check the network and contract address; a matching name or logo is not enough.'))+s('more','Search more records',p('Token keyword filters work on loaded pages. Use <strong>Load more</strong> to inspect more results. An empty filtered page does not mean the full history has no matches.'))+links([['preset-token-links','Follow a token source'],['keyword-rules','Filter token names']])),
};

workspacePages['overview'].updated='2026-09-25';
workspacePages['product-tour'].updated='2026-09-25';
